/* Generated by Yosys 0.46 (git sha1 e97731b9d, clang++ 16.0.0 -fPIC -O3) */

module control(clk, rstn, comp_out, restart, ramp_reset, ramp_en, busy, valid, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  output busy;
  wire busy;
  input clk;
  wire clk;
  input comp_out;
  wire comp_out;
  output [7:0] count;
  wire [7:0] count;
  output ramp_en;
  wire ramp_en;
  output ramp_reset;
  wire ramp_reset;
  input restart;
  wire restart;
  input rstn;
  wire rstn;
  wire [31:0] state_d;
  wire [4:0] state_q;
  output valid;
  wire valid;
  sky130_fd_sc_hs__clkinv_1 _37_ (
    .A(count[1]),
    .Y(_12_)
  );
  sky130_fd_sc_hs__clkinv_1 _38_ (
    .A(count[0]),
    .Y(_13_)
  );
  sky130_fd_sc_hs__clkinv_1 _39_ (
    .A(rstn),
    .Y(_01_)
  );
  sky130_fd_sc_hs__and3_1 _40_ (
    .A(rstn),
    .B(comp_out),
    .C(state_q[4]),
    .X(state_d[2])
  );
  sky130_fd_sc_hs__nand3_1 _41_ (
    .A(rstn),
    .B(restart),
    .C(state_q[3]),
    .Y(_14_)
  );
  sky130_fd_sc_hs__clkinv_1 _42_ (
    .A(_14_),
    .Y(_00_)
  );
  sky130_fd_sc_hs__nor2b_1 _43_ (
    .A(comp_out),
    .B_N(state_q[4]),
    .Y(_15_)
  );
  sky130_fd_sc_hs__or2_1 _44_ (
    .A(state_q[2]),
    .B(_15_),
    .X(_16_)
  );
  sky130_fd_sc_hs__o21ai_1 _45_ (
    .A1(state_q[2]),
    .A2(_15_),
    .B1(rstn),
    .Y(_17_)
  );
  sky130_fd_sc_hs__clkinv_1 _46_ (
    .A(_17_),
    .Y(_03_)
  );
  sky130_fd_sc_hs__nor2_1 _47_ (
    .A(state_q[1]),
    .B(state_q[0]),
    .Y(_18_)
  );
  sky130_fd_sc_hs__nand2b_1 _48_ (
    .A_N(restart),
    .B(state_q[3]),
    .Y(_19_)
  );
  sky130_fd_sc_hs__a21oi_1 _49_ (
    .A1(_18_),
    .A2(_19_),
    .B1(_01_),
    .Y(_02_)
  );
  sky130_fd_sc_hs__or2_1 _50_ (
    .A(rstn),
    .B(state_q[2]),
    .X(ramp_reset)
  );
  sky130_fd_sc_hs__nor2b_1 _51_ (
    .A(rstn),
    .B_N(state_q[4]),
    .Y(ramp_en)
  );
  sky130_fd_sc_hs__nor4_1 _52_ (
    .A(state_q[4]),
    .B(state_q[1]),
    .C(state_q[0]),
    .D(state_q[2]),
    .Y(_20_)
  );
  sky130_fd_sc_hs__nor2_1 _53_ (
    .A(rstn),
    .B(_20_),
    .Y(busy)
  );
  sky130_fd_sc_hs__nor2b_1 _54_ (
    .A(rstn),
    .B_N(state_q[1]),
    .Y(valid)
  );
  sky130_fd_sc_hs__o21bai_1 _55_ (
    .A1(_00_),
    .A2(_03_),
    .B1_N(state_d[2]),
    .Y(_21_)
  );
  sky130_fd_sc_hs__a21oi_1 _56_ (
    .A1(rstn),
    .A2(_16_),
    .B1(_02_),
    .Y(_22_)
  );
  sky130_fd_sc_hs__nor3_1 _57_ (
    .A(_03_),
    .B(_02_),
    .C(_21_),
    .Y(_23_)
  );
  sky130_fd_sc_hs__a211o_1 _58_ (
    .A1(_14_),
    .A2(_17_),
    .B1(_13_),
    .C1(state_d[2]),
    .X(_24_)
  );
  sky130_fd_sc_hs__nor2_1 _59_ (
    .A(_21_),
    .B(_22_),
    .Y(_25_)
  );
  sky130_fd_sc_hs__o21a_1 _60_ (
    .A1(count[0]),
    .A2(_25_),
    .B1(_24_),
    .X(_04_)
  );
  sky130_fd_sc_hs__nor3_1 _61_ (
    .A(_12_),
    .B(_22_),
    .C(_24_),
    .Y(_26_)
  );
  sky130_fd_sc_hs__a211oi_1 _62_ (
    .A1(_12_),
    .A2(_24_),
    .B1(_26_),
    .C1(_23_),
    .Y(_05_)
  );
  sky130_fd_sc_hs__o21bai_1 _63_ (
    .A1(count[2]),
    .A2(_26_),
    .B1_N(_23_),
    .Y(_27_)
  );
  sky130_fd_sc_hs__a21oi_1 _64_ (
    .A1(count[2]),
    .A2(_26_),
    .B1(_27_),
    .Y(_06_)
  );
  sky130_fd_sc_hs__and3_1 _65_ (
    .A(count[3]),
    .B(count[2]),
    .C(_26_),
    .X(_28_)
  );
  sky130_fd_sc_hs__a21oi_1 _66_ (
    .A1(count[2]),
    .A2(_26_),
    .B1(count[3]),
    .Y(_29_)
  );
  sky130_fd_sc_hs__nor3_1 _67_ (
    .A(_23_),
    .B(_28_),
    .C(_29_),
    .Y(_07_)
  );
  sky130_fd_sc_hs__and4_1 _68_ (
    .A(count[4]),
    .B(count[3]),
    .C(count[2]),
    .D(_26_),
    .X(_30_)
  );
  sky130_fd_sc_hs__nor2_1 _69_ (
    .A(count[4]),
    .B(_28_),
    .Y(_31_)
  );
  sky130_fd_sc_hs__nor3_1 _70_ (
    .A(_23_),
    .B(_30_),
    .C(_31_),
    .Y(_08_)
  );
  sky130_fd_sc_hs__o21bai_1 _71_ (
    .A1(count[5]),
    .A2(_30_),
    .B1_N(_23_),
    .Y(_32_)
  );
  sky130_fd_sc_hs__a21oi_1 _72_ (
    .A1(count[5]),
    .A2(_30_),
    .B1(_32_),
    .Y(_09_)
  );
  sky130_fd_sc_hs__and3_1 _73_ (
    .A(count[6]),
    .B(count[5]),
    .C(_30_),
    .X(_33_)
  );
  sky130_fd_sc_hs__a21oi_1 _74_ (
    .A1(count[5]),
    .A2(_30_),
    .B1(count[6]),
    .Y(_34_)
  );
  sky130_fd_sc_hs__nor3_1 _75_ (
    .A(_23_),
    .B(_33_),
    .C(_34_),
    .Y(_10_)
  );
  sky130_fd_sc_hs__and4_1 _76_ (
    .A(count[7]),
    .B(count[6]),
    .C(count[5]),
    .D(_30_),
    .X(_35_)
  );
  sky130_fd_sc_hs__a31oi_1 _77_ (
    .A1(count[6]),
    .A2(count[5]),
    .A3(_30_),
    .B1(count[7]),
    .Y(_36_)
  );
  sky130_fd_sc_hs__nor3_1 _78_ (
    .A(_23_),
    .B(_35_),
    .C(_36_),
    .Y(_11_)
  );
  sky130_fd_sc_hs__dfxtp_1 _79_ (
    .CLK(clk),
    .D(_01_),
    .Q(state_q[0])
  );
  sky130_fd_sc_hs__dfxtp_1 _80_ (
    .CLK(clk),
    .D(state_d[2]),
    .Q(state_q[1])
  );
  sky130_fd_sc_hs__dfxtp_1 _81_ (
    .CLK(clk),
    .D(_00_),
    .Q(state_q[2])
  );
  sky130_fd_sc_hs__dfxtp_1 _82_ (
    .CLK(clk),
    .D(_02_),
    .Q(state_q[3])
  );
  sky130_fd_sc_hs__dfxtp_1 _83_ (
    .CLK(clk),
    .D(_03_),
    .Q(state_q[4])
  );
  sky130_fd_sc_hs__dfxtp_1 _84_ (
    .CLK(clk),
    .D(_04_),
    .Q(count[0])
  );
  sky130_fd_sc_hs__dfxtp_1 _85_ (
    .CLK(clk),
    .D(_05_),
    .Q(count[1])
  );
  sky130_fd_sc_hs__dfxtp_1 _86_ (
    .CLK(clk),
    .D(_06_),
    .Q(count[2])
  );
  sky130_fd_sc_hs__dfxtp_1 _87_ (
    .CLK(clk),
    .D(_07_),
    .Q(count[3])
  );
  sky130_fd_sc_hs__dfxtp_1 _88_ (
    .CLK(clk),
    .D(_08_),
    .Q(count[4])
  );
  sky130_fd_sc_hs__dfxtp_1 _89_ (
    .CLK(clk),
    .D(_09_),
    .Q(count[5])
  );
  sky130_fd_sc_hs__dfxtp_1 _90_ (
    .CLK(clk),
    .D(_10_),
    .Q(count[6])
  );
  sky130_fd_sc_hs__dfxtp_1 _91_ (
    .CLK(clk),
    .D(_11_),
    .Q(count[7])
  );
  assign state_d[31:3] = 29'h00000000;
endmodule
